import { useState, useEffect } from "react";
import { Trophy, Target, Flame, BookOpen, TrendingUp, Share2, Copy, Check } from "lucide-react";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { Skeleton } from "@/components/ui/skeleton";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";

interface StudentProgressDialogProps {
  studentUserId: string;
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

export default function StudentProgressDialog({ studentUserId, open, onOpenChange }: StudentProgressDialogProps) {
  const [data, setData] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    if (!open || !studentUserId) return;
    setLoading(true);

    const fetch = async () => {
      try {
        const { data: result, error } = await supabase.rpc("get_student_progress", {
          p_student_user_id: studentUserId,
        });
        if (error) throw error;
        setData(result);
      } catch (err) {
        console.error("Failed to fetch student progress:", err);
      } finally {
        setLoading(false);
      }
    };
    fetch();
  }, [open, studentUserId]);

  const handleShare = () => {
    if (!data) return;
    const p = data.profile;
    const q = data.quiz_stats;
    const text = `📊 Student Progress Report - ${p?.name || "Student"}
━━━━━━━━━━━━━━━━━━
🏆 Level ${p?.level || 1} | ${p?.total_xp || 0} XP | 🔥${p?.streak || 0} streak
📝 Quizzes: ${q?.total_quizzes || 0} completed
📈 Average Score: ${q?.average_score || 0}%
🎯 Best Score: ${q?.best_score || 0}%
✅ Accuracy: ${q?.total_questions ? ((q?.total_correct / q?.total_questions) * 100).toFixed(1) : 0}%
━━━━━━━━━━━━━━━━━━
Generated by BrainBuddy`;

    navigator.clipboard.writeText(text);
    setCopied(true);
    toast.success("Progress report copied to clipboard!");
    setTimeout(() => setCopied(false), 2000);
  };

  const profile = data?.profile;
  const stats = data?.quiz_stats;
  const recentQuizzes = data?.recent_quizzes || [];
  const topicMastery = data?.topic_mastery || [];

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl max-h-[85vh] overflow-auto">
        <DialogHeader>
          <div className="flex items-center justify-between">
            <DialogTitle className="flex items-center gap-2">
              <TrendingUp className="h-5 w-5 text-primary" />
              Student Progress
            </DialogTitle>
            <Button variant="outline" size="sm" onClick={handleShare} className="gap-1.5">
              {copied ? <Check className="h-3.5 w-3.5" /> : <Share2 className="h-3.5 w-3.5" />}
              {copied ? "Copied" : "Share"}
            </Button>
          </div>
        </DialogHeader>

        {loading ? (
          <div className="space-y-4">
            <Skeleton className="h-20" />
            <div className="grid grid-cols-2 gap-3">{[1, 2, 3, 4].map(i => <Skeleton key={i} className="h-24" />)}</div>
          </div>
        ) : (
          <div className="space-y-5">
            {/* Profile header */}
            <div className="flex items-center gap-4 p-4 rounded-xl bg-muted/30 border border-border/50">
              <div className="h-14 w-14 rounded-full bg-primary/10 flex items-center justify-center text-2xl font-bold text-primary">
                {(profile?.name || "?")[0]?.toUpperCase()}
              </div>
              <div className="flex-1">
                <h3 className="text-lg font-bold">{profile?.name || "Student"}</h3>
                <div className="flex items-center gap-3 text-sm text-muted-foreground">
                  <span>Level {profile?.level || 1}</span>
                  <span>•</span>
                  <span>{profile?.rank || "Novice"}</span>
                  <span>•</span>
                  <span>🔥 {profile?.streak || 0} day streak</span>
                </div>
              </div>
              <div className="text-right">
                <p className="text-2xl font-bold text-primary">{profile?.total_xp || 0}</p>
                <p className="text-[10px] text-muted-foreground">Total XP</p>
              </div>
            </div>

            {/* Stats grid */}
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
              {[
                { label: "Quizzes", value: stats?.total_quizzes || 0, icon: BookOpen },
                { label: "Avg Score", value: `${Number(stats?.average_score || 0).toFixed(0)}%`, icon: Target },
                { label: "Best Score", value: `${Number(stats?.best_score || 0).toFixed(0)}%`, icon: Trophy },
                { label: "Best Streak", value: stats?.longest_streak || 0, icon: Flame },
              ].map(s => (
                <Card key={s.label} className="border-border/50">
                  <CardContent className="p-3 text-center">
                    <s.icon className="h-5 w-5 mx-auto mb-1 text-muted-foreground" />
                    <p className="text-xl font-bold">{s.value}</p>
                    <p className="text-[10px] text-muted-foreground">{s.label}</p>
                  </CardContent>
                </Card>
              ))}
            </div>

            {/* Accuracy */}
            {stats && stats.total_questions > 0 && (
              <Card className="border-border/50">
                <CardContent className="p-4">
                  <div className="flex items-center justify-between mb-2">
                    <p className="text-sm font-medium">Overall Accuracy</p>
                    <p className="text-sm font-bold">
                      {((stats.total_correct / stats.total_questions) * 100).toFixed(1)}%
                    </p>
                  </div>
                  <Progress value={(stats.total_correct / stats.total_questions) * 100} className="h-2" />
                  <p className="text-[10px] text-muted-foreground mt-1">
                    {stats.total_correct} correct out of {stats.total_questions} questions
                  </p>
                </CardContent>
              </Card>
            )}

            {/* Topic mastery */}
            {topicMastery.length > 0 && (
              <div>
                <h4 className="text-sm font-semibold mb-3">Topic Mastery</h4>
                <div className="space-y-2">
                  {topicMastery.map((t: any, i: number) => (
                    <div key={i} className="flex items-center gap-3 p-2 rounded-md bg-muted/20">
                      <div className="flex-1">
                        <p className="text-sm font-medium">{t.topic_name}</p>
                        <p className="text-[10px] text-muted-foreground">{t.quizzes_completed} quizzes</p>
                      </div>
                      <div className="w-24">
                        <Progress value={Number(t.average_score)} className="h-1.5" />
                      </div>
                      <p className="text-xs font-semibold w-10 text-right">{Number(t.average_score).toFixed(0)}%</p>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Recent quizzes */}
            {recentQuizzes.length > 0 && (
              <div>
                <h4 className="text-sm font-semibold mb-3">Recent Quizzes</h4>
                <div className="space-y-1.5">
                  {recentQuizzes.slice(0, 10).map((q: any, i: number) => (
                    <div key={i} className="flex items-center justify-between p-2 rounded-md bg-muted/20 text-sm">
                      <div className="flex items-center gap-2">
                        <Badge variant="outline" className="text-[10px]">{q.difficulty || "medium"}</Badge>
                        <span className="text-muted-foreground">{q.correct_answers}/{q.total_questions}</span>
                      </div>
                      <div className="flex items-center gap-2">
                        <span className={`font-semibold ${Number(q.score) >= 80 ? "text-green-500" : Number(q.score) >= 50 ? "text-yellow-500" : "text-destructive"}`}>
                          {Number(q.score).toFixed(0)}%
                        </span>
                        <span className="text-[10px] text-muted-foreground">
                          {new Date(q.created_at).toLocaleDateString()}
                        </span>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>
        )}
      </DialogContent>
    </Dialog>
  );
}
