import { useState } from "react";
import {
  FileText,
  Sparkles,
  Loader2,
  Copy,
  Check,
  BookOpen,
  Download,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Input } from "@/components/ui/input";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";
import { FILTER_OPTIONS } from "@/contexts/FilterContext";
import ReactMarkdown from "react-markdown";
import BattleLoadingOverlay from "@/components/battle/BattleLoadingOverlay";
import jsPDF from "jspdf";

const AINotes = () => {
  const [subject, setSubject] = useState("");
  const [classLevel, setClassLevel] = useState("");
  const [topic, setTopic] = useState("");
  const [notes, setNotes] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [copied, setCopied] = useState(false);

  const subjectsForClass = classLevel
    ? FILTER_OPTIONS.subjects[classLevel] || []
    : [];

  const generateNotes = async () => {
    if (!topic.trim() || isLoading) return;

    setIsLoading(true);
    setNotes("");

    try {
      const { data, error } = await supabase.functions.invoke("ai-notes-gen", {
        body: {
          topic: topic.trim(),
          subject: subject || undefined,
          classLevel: classLevel || undefined,
        },
      });

      if (error) throw error;

      if (data?.notes) {
        setNotes(data.notes);
      } else {
        throw new Error("No notes returned");
      }
    } catch (err: any) {
      console.error("Notes generation error:", err);
      if (err?.message?.includes("429") || err?.status === 429) {
        toast.error("Rate limit reached. Please wait a moment.");
      } else if (err?.message?.includes("402") || err?.status === 402) {
        toast.error("Credits exhausted. Please add funds.");
      } else {
        toast.error("Failed to generate notes");
      }
    } finally {
      setIsLoading(false);
    }
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(notes);
    setCopied(true);
    toast.success("Notes copied!");
    setTimeout(() => setCopied(false), 2000);
  };

  const downloadNotesPDF = () => {
    if (!notes) return;

    const doc = new jsPDF({ unit: "mm", format: "a4" });
    const pageW = doc.internal.pageSize.getWidth();
    const pageH = doc.internal.pageSize.getHeight();
    const marginL = 18;
    const marginR = 18;
    const maxW = pageW - marginL - marginR;
    let y = 20;

    const addPage = () => {
      doc.addPage();
      y = 20;
    };

    const checkPage = (needed: number) => {
      if (y + needed > pageH - 20) {
        addPage();
      }
    };

    // Title header bar
    doc.setFillColor(37, 99, 235);
    doc.rect(0, 0, pageW, 32, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(20);
    doc.setFont("helvetica", "bold");
    const title = topic.length > 50 ? topic.slice(0, 50) + "..." : topic;
    doc.text(title, pageW / 2, 14, { align: "center" });
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    const subtitle = [subject, classLevel].filter(Boolean).join(" • ") || "Study Notes";
    doc.text(subtitle, pageW / 2, 22, { align: "center" });
    doc.setFontSize(7);
    doc.text(`Generated by BrainBuddy • ${new Date().toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" })}`, pageW / 2, 28, { align: "center" });

    y = 40;

    // Parse markdown into structured blocks
    const lines = notes.split("\n");

    for (const line of lines) {
      const trimmed = line.trimEnd();

      // H2 Heading
      if (trimmed.startsWith("## ")) {
        checkPage(16);
        y += 4;
        // Accent bar
        doc.setFillColor(37, 99, 235);
        doc.rect(marginL, y, 3, 8, "F");
        doc.setTextColor(30, 58, 138);
        doc.setFontSize(13);
        doc.setFont("helvetica", "bold");
        doc.text(trimmed.replace(/^## /, ""), marginL + 6, y + 6);
        y += 12;
        // Underline
        doc.setDrawColor(37, 99, 235);
        doc.setLineWidth(0.4);
        doc.line(marginL, y, pageW - marginR, y);
        y += 4;
        continue;
      }

      // H3 Heading
      if (trimmed.startsWith("### ")) {
        checkPage(12);
        y += 3;
        doc.setTextColor(55, 65, 81);
        doc.setFontSize(11);
        doc.setFont("helvetica", "bold");
        doc.text(trimmed.replace(/^### /, ""), marginL + 2, y + 5);
        y += 10;
        continue;
      }

      // Bullet points
      if (trimmed.startsWith("- ") || trimmed.startsWith("* ")) {
        checkPage(8);
        const text = trimmed.replace(/^[-*]\s+/, "").replace(/\*\*/g, "");
        doc.setTextColor(55, 65, 81);
        doc.setFontSize(9.5);

        // Check if has bold prefix (key: value pattern)
        const boldMatch = text.match(/^(.+?):\s*(.+)$/);

        if (boldMatch) {
          // Bullet dot
          doc.setFillColor(37, 99, 235);
          doc.circle(marginL + 3, y + 2.5, 1.2, "F");

          doc.setFont("helvetica", "bold");
          const keyText = boldMatch[1] + ": ";
          const keyWidth = doc.getTextWidth(keyText);
          doc.text(keyText, marginL + 7, y + 3.5);

          doc.setFont("helvetica", "normal");
          const valueLines = doc.splitTextToSize(boldMatch[2], maxW - 7 - keyWidth);
          doc.text(valueLines[0], marginL + 7 + keyWidth, y + 3.5);
          y += 6;

          // Wrap remaining lines
          for (let i = 1; i < valueLines.length; i++) {
            checkPage(6);
            doc.text(valueLines[i], marginL + 10, y + 3.5);
            y += 5;
          }
        } else {
          doc.setFillColor(37, 99, 235);
          doc.circle(marginL + 3, y + 2.5, 1.2, "F");
          doc.setFont("helvetica", "normal");
          const wrappedLines = doc.splitTextToSize(text, maxW - 7);
          wrappedLines.forEach((wl: string, i: number) => {
            checkPage(6);
            doc.text(wl, marginL + 7, y + 3.5);
            y += 5;
          });
        }
        y += 1;
        continue;
      }

      // Empty lines
      if (trimmed === "") {
        y += 3;
        continue;
      }

      // Regular paragraph text
      checkPage(8);
      doc.setTextColor(55, 65, 81);
      doc.setFontSize(9.5);
      doc.setFont("helvetica", "normal");
      // Strip bold markers for clean PDF
      const cleanText = trimmed.replace(/\*\*/g, "");
      const wrappedLines = doc.splitTextToSize(cleanText, maxW);
      wrappedLines.forEach((wl: string) => {
        checkPage(6);
        doc.text(wl, marginL, y + 3.5);
        y += 5;
      });
      y += 1;
    }

    // Footer on all pages
    const totalPages = doc.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      doc.setPage(i);
      doc.setFontSize(7);
      doc.setTextColor(156, 163, 175);
      doc.setFont("helvetica", "italic");
      doc.text("BrainBuddy AI Notes", marginL, pageH - 8);
      doc.text(`Page ${i} of ${totalPages}`, pageW - marginR, pageH - 8, { align: "right" });
      // Bottom accent line
      doc.setDrawColor(37, 99, 235);
      doc.setLineWidth(0.5);
      doc.line(marginL, pageH - 12, pageW - marginR, pageH - 12);
    }

    const fileName = `${(topic || "Notes").replace(/[^a-zA-Z0-9]/g, "_").slice(0, 40)}_Notes.pdf`;
    doc.save(fileName);
    toast.success("Notes PDF downloaded!");
  };

  return (
    <div className="flex flex-col h-[calc(100vh-3.5rem)]">
      <BattleLoadingOverlay
        show={isLoading}
        message="Generating Notes..."
        subMessage="AI is creating structured, exam-ready notes for you"
      />

      {/* Header */}
      <div className="px-6 py-4 border-b border-border/50">
        <div className="flex items-center gap-3 mb-4">
          <div className="p-2 rounded-lg bg-primary/10">
            <FileText className="h-5 w-5 text-primary" />
          </div>
          <div>
            <h1 className="font-bold text-lg">AI Notes Generator</h1>
            <p className="text-xs text-muted-foreground">
              Ultra-fast, exam-ready notes for any subject
            </p>
          </div>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 mb-3">
          <Select
            value={classLevel}
            onValueChange={(v) => {
              setClassLevel(v);
              setSubject("");
            }}
          >
            <SelectTrigger>
              <SelectValue placeholder="Class / Level" />
            </SelectTrigger>
            <SelectContent>
              {FILTER_OPTIONS.classes.map((c) => (
                <SelectItem key={c} value={c}>
                  {c}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>

          <Select
            value={subject}
            onValueChange={setSubject}
            disabled={!classLevel}
          >
            <SelectTrigger>
              <SelectValue placeholder="Subject" />
            </SelectTrigger>
            <SelectContent>
              {subjectsForClass.map((s) => (
                <SelectItem key={s} value={s}>
                  {s}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>

          <Input
            placeholder="Chapter / Topic"
            value={topic}
            onChange={(e) => setTopic(e.target.value)}
            onKeyDown={(e) => e.key === "Enter" && generateNotes()}
          />
        </div>

        <Button
          variant="neon"
          onClick={generateNotes}
          disabled={isLoading || !topic.trim()}
          className="w-full sm:w-auto"
        >
          {isLoading ? (
            <>
              <Loader2 className="h-4 w-4 animate-spin mr-2" />
              Generating...
            </>
          ) : (
            <>
              <Sparkles className="h-4 w-4 mr-2" />
              Generate Notes
            </>
          )}
        </Button>
      </div>

      {/* Notes output */}
      <ScrollArea className="flex-1 px-6 py-4">
        {!notes && !isLoading && (
          <div className="flex flex-col items-center justify-center h-full gap-4 py-16">
            <BookOpen className="h-12 w-12 text-muted-foreground" />
            <p className="text-muted-foreground text-center max-w-sm">
              Select a subject and topic, then hit Generate to get structured,
              exam-ready notes instantly.
            </p>
          </div>
        )}

        {notes && (
          <div className="max-w-3xl mx-auto space-y-4">
            <div className="flex justify-end gap-2">
              <Button variant="outline" size="sm" onClick={downloadNotesPDF}>
                <Download className="h-4 w-4 mr-1" />
                Download PDF
              </Button>
              <Button variant="outline" size="sm" onClick={handleCopy}>
                {copied ? (
                  <Check className="h-4 w-4 mr-1" />
                ) : (
                  <Copy className="h-4 w-4 mr-1" />
                )}
                {copied ? "Copied" : "Copy"}
              </Button>
            </div>
            <div className="glass-card rounded-2xl p-6 prose prose-sm prose-invert max-w-none">
              <ReactMarkdown>{notes}</ReactMarkdown>
            </div>
          </div>
        )}
      </ScrollArea>
    </div>
  );
};

export default AINotes;